#!/bin/sh

specfile=mlogd

version=$(grep Version ${specfile}.spec | head -1 | awk -F: '{print $2}' | cut -b2-)

fullname=${specfile}-${version}

git clone . /var/tmp/$fullname || exit 1
rm -rf /var/tmp/$fullname/.git*

dest=$HOME/rpms/SOURCES/${fullname}.tar.gz
rm -f $dest
tar -C /var/tmp -zcvf $dest $fullname && rm -rf /var/tmp/$fullname

rpmbuild -ta $dest 
